
server:
  port: 8888
spring:
  application:
    name: project-buyer


  datasource:
    url: jdbc:mysql://101.43.42.54:3306/flight-project?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 101.43.42.54
    port: 6379

##mybaites-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

### 腾讯cos
tengxun:
  cos:
    secretId: AKIDb0B7nDOJzPaVBbmhNnzwd5HDuLXT9alg
    secretKey: h9LHyPaWCcmhMlvpUt3yykGXYJo44oJY
    bucket: ap-shanghai
    bucketName: xingqiu-tuchuang-1256524210
    prefix: /3937


